config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "photos#index"
  resources :photos, only: [ :index ]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    if params[:random_img]
      @random_img = Unsplash::Photo.random
    end

    if params[:img_search_word]
      @random_img = nil
      @search_imgs = Unsplash::Photo.search(params[:img_search_word])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rinder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_img.html.erb
<%= image_tag img['urls']['small'], alt: img['description'] %>
<p><%= img['user']['name'] %></p>

app/views/photos/_search_imgs.html.erb
<% search_imgs.each do |img| %>
  <div class="search">
    <%= render "img", img: img%>
  </div>
<% end %>

app/views/photos/index.html.erb
<h1>Photos</h1>

<div>
  <%= link_to "Generate Random Image", photos_path(random_img: true), method: :get%>
  <% if @random_img %>
      <%= link_to "Delete Random Image", photos_path, method: :get%>
  <% end %>
</div>

<div>
  <%= form_with url: root_path, method: :get do |form| %>
    <%= form.hidden_field :random_img, value: false %> 
    <%= form.text_field :img_search_word, placeholder: "Search for images" %>
    <%= form.submit "Search" %>
  <% end %>
</div>


<% if @random_img %>
  <div class="random">
    <%= render "img", img: @random_img%>
  </div>
<% end %>

<% if @search_imgs %>
  <div>
    <%= render "search_imgs", search_imgs: @search_imgs%>
  </div>
<% end %>